updating test scripts, confirming rightful computations

diff --git a/testing/addedNodes/subMake b/testing/addedNodes/subMake
--- a/testing/addedNodes/subMake
+++ b/testing/addedNodes/subMake
@@ -1,56 +1,68 @@
 
 
+test: testConedy testPython-Conedy
 
-test:
+
+testConedy:
 	mkdir -p output
 	mkdir -p expected
 	mkdir -p results
-	find  -maxdepth 1 -name '*.ns' -exec make -s test_{} \;
-	find  -maxdepth 1 -name '*.py' -exec make -s testPython_{} \;
-#	sum output/* > ergebnis_checksumme
-#	diff ergebnis_checksumme erwartet_checksumme
+	find  -maxdepth 1 -name '*.co' -exec make -s test_{} \;
+
+
+testPython-Conedy:
+	mkdir -p output
+	mkdir -p expected
+	mkdir -p results
+	find  -maxdepth 1 -name '*.py' -exec make -s test_{} \;
 
 
 
 
 
-testPython_./%:
-	sed 's/import conedy as ns/import conedy as ns\nns.setRandomSeed(0)/' $* | python > output/$*.out 2> output/$*.err
-	sed -i "/#/d" output/$*.out
-	sum output/$**  > results/sum_$* 
-	sed "s/fileName.py/$*/" expected/sum_template.py > expected/sum_$*
-	if [ "`diff expected/sum_$* results/sum_$*`" = "" ]; then \
-			echo "test `pwd`/$* succeded"; \
-		else echo "test `pwd`/$* failed !"; diff expected/sum_$* results/sum_$*; \
-	fi; \
 
 
 
-test_./%:
-	(echo "set RandomSeed(0)";cat $*) | conedy $* > output/$*.out 2> output/$*.err
-	sed -i "/#/d" output/$*.out
-	sum output/$** > results/sum_$* 
-	if [ -e "expected/sum_$*" ]; then \
-		if [ "`diff expected/sum_$* results/sum_$*`" = "" ]; then echo "test `pwd`/$* succeded"; else echo "test `pwd`/$* failed !"; diff expected/sum_$* results/sum_$*;  fi \
+
+test_./%.py:
+	sed 's/import conedy as co/import conedy as co\nco.setRandomSeed(0)/' $*.py | python > output/$*.py.out 2> output/$*.py.err || true
+	sed -i "/#/d" output/$*.py.out
+	sum output/$*.py*  > results/sum_$*.py 
+	if [ -e "expected/sum_$*.py" ]; then \
+		if [ "`diff expected/sum_$*.py results/sum_$*.py`" = "" ]; then \
+			echo "test `pwd`/$*.py succeded"; \
+		else echo "test `pwd`/$*.py failed !"; diff expected/sum_$*.py results/sum_$*.py; \
+		fi; \
+	else echo "warning checksum for $*.py not present !"; \
+	fi
+
+test_./%.co:
+	(echo "setRandomSeed(0);";cat $*.co) | conedy  > output/$*.co.out 2> output/$*.co.err || true
+	sed -i "/#/d" output/$*.co.out
+	sum output/$*.co* > results/sum_$*.co 
+	if [ -e "expected/sum_$*.co" ]; then \
+		if [ "`diff expected/sum_$*.co results/sum_$*.co`" = "" ]; then echo "test `pwd`/$*.co succeded"; else echo "test `pwd`/$*.co failed !"; diff expected/sum_$*.co results/sum_$*.co;  fi \
 	else \
-		echo "warning checksum for $* not present !"; \
+		echo "warning checksum for $*.co not present !"; \
 	fi
 		
 
 confirm_./%.py:
-	sed 's/import conedy as ns/import conedy as ns\nns.setRandomSeed(0)/' $*.py | python > output/$*.py.out 2> output/$*.py.err
+	sed 's/import conedy as co/import conedy as co\nco.setRandomSeed(0)/' $*.py | python > output/$*.py.out 2> output/$*.py.err || true
 	sed -i "/#/d" output/$*.py.out
 	sum output/$*.py* >  expected/sum_$*.py
 	
-confirm_./%.ns:
-	(echo "set RandomSeed(0)";cat $*.ns) | conedy $*.ns > output/$*.ns.out 2> output/$*.ns.err
-	sed -i "/#/d" output/$*.ns.out
-	sum output/$*.ns* >  expected/sum_$*.ns
+confirm_./%.co:
+	(echo "setRandomSeed(0);";cat $*.co) | conedy  > output/$*.co.out 2> output/$*.co.err || true
+	sed -i "/#/d" output/$*.co.out
+	sum output/$*.co* >  expected/sum_$*.co
+
+
 
 
 
 submit:
-	cd expected; svn add --parents sum_template.py
+	cd expected; git add sum_template.py
 
 
 
